version: 2
updates:
  - package-ecosystem: npm
    directory: /plugin-frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /plugin_app
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: maven
    directory: /plugin-backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: gradle
    directory: /plugin_app/android
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /plugin-backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
