package com.plugin.dto.response;

import lombok.Builder;
import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data @Builder
public class BookingResponse {
    private Long id;
    private String referenceId;
    private Long customerId;
    private String customerName;
    private Long stationId;
    private String stationName;
    private String gridRegion;
    private Long chargingPointId;
    private String chargingPointIdentifier;
    private String pointType;
    private Long vehicleId;
    private String vehicleNickname;
    private String vehicleMake;
    private String vehicleModel;
    private String vehicleRegistration;
    private LocalDateTime startTime;
    private LocalDateTime endTime;
    private LocalDateTime reservedUntil;
    private LocalDateTime holdExpiresAt;
    private Boolean etaLiveTraffic;
    private Long waitSeconds;
    private Integer requestedDurationMinutes;
    private Double originLatitude;
    private Double originLongitude;
    private Double lastKnownLatitude;
    private Double lastKnownLongitude;
    private LocalDateTime lastLocationPingAt;
    private LocalDateTime predictedArrivalAt;
    private LocalDateTime gracePeriodEndTime;
    private Long etaSeconds;
    private Double lastDistanceMeters;
    private Boolean proximityLocked;
    private Long assignedChargingPointId;
    private Boolean virtualSpot;
    private BigDecimal lockedRatePerUnit;
    private BigDecimal baseRatePerUnit;
    private BigDecimal lockedDiscountPercent;
    private String lockedRateType;
    private String chargingPreference;
    private BigDecimal requestedEnergyKwh;
    private BigDecimal expectedRenewableSharePercent;
    private BigDecimal baselineRenewableSharePercent;
    private BigDecimal expectedCarbonKg;
    private BigDecimal estimatedCarbonSavedKg;
    private Integer greenScore;
    private String energyDataMode;
    private String energySource;
    private String energyQuality;
    private LocalDateTime energyCapturedAt;
    private String status;
    private String cancellationReason;
    private String rescheduleRequestStatus;
    private LocalDateTime rescheduleRequestedStartTime;
    private LocalDateTime rescheduleRequestedEndTime;
    private String rescheduleRequestReason;
    private LocalDateTime rescheduleRequestedAt;
    private LocalDateTime rescheduleReviewedAt;
    private String rescheduleReviewedBy;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
