const mapStyleLight = [
  { elementType: 'geometry', stylers: [{ color: '#F9F6F0' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#2D2D2D' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#FFFFFF' }, { weight: 3 }] },
  { featureType: 'administrative', elementType: 'geometry.stroke', stylers: [{ color: '#C9C9C9' }, { weight: 1 }] },
  { featureType: 'administrative.land_parcel', elementType: 'labels', stylers: [{ visibility: 'off' }] },
  { featureType: 'landscape', elementType: 'geometry', stylers: [{ color: '#F9F6F0' }] },
  { featureType: 'landscape.man_made', elementType: 'geometry', stylers: [{ color: '#FAF7F2' }] },
  { featureType: 'poi', elementType: 'geometry', stylers: [{ color: '#F4F1EA' }] },
  { featureType: 'poi', elementType: 'labels.icon', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi.business', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi.attraction', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi.medical', elementType: 'labels', stylers: [{ visibility: 'simplified' }] },
  { featureType: 'poi.school', elementType: 'labels', stylers: [{ visibility: 'simplified' }] },
  { featureType: 'poi.government', elementType: 'labels', stylers: [{ visibility: 'simplified' }] },
  { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#E8F5E9' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#FFFFFF' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#E8E8E8' }, { weight: 1 }] },
  { featureType: 'road', elementType: 'labels.icon', stylers: [{ visibility: 'on' }] },
  { featureType: 'road.arterial', elementType: 'geometry', stylers: [{ color: '#F5F5F5' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#FFF3CD' }] },
  { featureType: 'road.highway', elementType: 'geometry.stroke', stylers: [{ color: '#E7DFAE' }, { weight: 1 }] },
  { featureType: 'road.local', elementType: 'geometry', stylers: [{ color: '#FFFFFF' }] },
  { featureType: 'transit.line', elementType: 'geometry', stylers: [{ color: '#4DB6AC' }] },
  { featureType: 'transit.station', elementType: 'labels', stylers: [{ visibility: 'simplified' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#DDEEFF' }] },
];

export default mapStyleLight;
