package com.plugin.enums;

public enum StationManagerFileSlot {
    GOVERNMENT_ID_DOCUMENT,
    SELFIE_DOCUMENT,
    REGISTRATION_PROOF,
    AUTHORIZATION_PROOF,
    PROPERTY_DOCUMENT,
    ELECTRICITY_BILL,
    BANK_PROOF,
    INSTALLATION_PHOTO,
    SITE_PHOTO,
    BUSINESS_DOCUMENT
}
