package com.plugin.enums;

public enum StationManagerBusinessDocumentType {
    INDIVIDUAL_ID_PROOF,
    PROPRIETORSHIP_REGISTRATION_PROOF,
    UDYAM_REGISTRATION,
    SHOP_ESTABLISHMENT_LICENSE,
    GST_CERTIFICATE,
    PARTNERSHIP_REGISTRATION_CERTIFICATE,
    PARTNERSHIP_DEED,
    LLP_CERTIFICATE_OF_INCORPORATION,
    LLP_AGREEMENT,
    COMPANY_CERTIFICATE_OF_INCORPORATION,
    MEMORANDUM_OF_ASSOCIATION,
    ARTICLES_OF_ASSOCIATION,
    BOARD_RESOLUTION,
    AUTHORIZATION_LETTER
}
